#!/bin/sh

OPTIND=1

name=""
file=""

while getopts "n:f:" opt; do
	case $opt in
		n)
			name=$OPTARG
			;;
		f)	file=$OPTARG
			;;
	esac
done

shift $((OPTIND-1))

if [[ $name="" || $file="" ]];
then
	sudo ln -s $(realpath $1) /usr/bin/$1
else
	sudo ln -s $(realpath $file) /usr/bin/$name
fi

[ "${1:-}" = "--" ] && shift

