#!/bin/sh

pagecount=$1

i=1

while [ $i -le $pagecount ]
do
	sh -c "curl http://funquizzes.fun/uploads/manga/Dragon%20Ball%20-%20Perfect%20Edition/Manga%20Dragon%20Ball%20-%20Perfect%20Edition/0034/$(printf "%03d" $i).jpg --output /home/lucas/dragonball/01/$i.jpg"
	i=$((i+1))
done
