#!/bin/bash

filename="/home/lucas/screencapture/$(date -u +%F_%T).mkv"

if pgrep -x "ffmpeg" > /dev/null
then
	notify-send "Recording saved to /home/lucas/screencapture/"
	killall ffmpeg
else
	notify-send "Recording started."
	ffmpeg -f x11grab -s 1600x900 -i :0.0 -f alsa -i hw:0 "$filename"
fi
