#!/bin/bash

id=$(wmctrl -l | grep -oP "(?<=)(0x\w+)(?=.*Chromium)")
xdotool key --window $id "ctrl+l"
xdotool key --window $id "ctrl+c"

url=$(xclip -selection c -o)

if echo $url | grep -q 'https://www.youtube.com/watch?v=.*$' 
then
  response=$(printf "Yes\nNo" | dmenu -p "Open in mpv?");
  if [ $response == 'Yes' ]
  then
    mpv --autofit-larger=70%x60% --ytdl-format="bestvideo[height<=?1080]+bestaudio/best" $url
  else
    exit 1
  fi
else
  notify-send "$url is not a YouTube URL...";
fi

